spring:
  datasource:
    url: jdbc:postgresql://db_emission:5432/cfemission
    username: docker
    password: docker
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

gateway_url: ${API_GATEWAY_URL:http://localhost:8000}

server:
  port: 8001