spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: emission-service
          uri: lb:http://EMISSION-SERVICE
          predicates:
            - Path=/cfemission/**
          filters:
            - RewritePath=/cfemission/(?<remaining>.*), /${remaining}
        - id: storage-service
          uri: lb:http://STORAGE-SERVICE
          predicates:
            - Path=/cfstorage/**
          filters:
            - RewritePath=/cfstorage/(?<remaining>.*), /${remaining}
        - id: registry-service
          uri: lb:http://REGISTRY-SERVICE
          predicates:
            - Path=/cfregistry/**
          filters:
            - RewritePath=/cfregistry/(?<remaining>.*), /${remaining}
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN_FIRST

  datasource:
    url: jdbc:postgresql://db_gateway:5432/cfgateway
    username: docker
    password: docker
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

gateway_url: ${API_GATEWAY_URL:http://localhost:8000}

frontend_url: ${FRONTEND_URL:http://localhost:3000}

jwt:
  secret: ffc8faeefff096f390265fb9f0dd6fbe2abf7146bf9ad8ba276a6e4366b2dfc5

server:
  port: 8000
