spring:
  datasource:
    url: jdbc:postgresql://db_registry:5432/cfregistry
    username: docker
    password: docker
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

gateway_url: ${API_GATEWAY_URL:http://localhost:8040}
frontend_url: ${FRONTEND_URL:http://localhost:3000}

jwt:
  secret: ffc8faeefff096f390265fb9f0dd6fbe2abf7146bf9ad8ba276a6e4366b2dfc5

server:
  port: 8004